services:
  grafitodb:
    image: postgres:15
    platform: linux/arm64/v8
    container_name: grafitodb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: grafitodb
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
